server:
  port: ${SERVER_PORT:${BACKEND_PORT:8080}}
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:backend/.env[.properties]
      - optional:file:../backend/.env[.properties]
      - optional:file:../../backend/.env[.properties]
  application:
    name: hack-backend
  datasource:
    url: jdbc:h2:mem:hackdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      encoding: UTF-8

openai:
  api-key: ${OPENAI_API_KEY:}
  base-url: https://api.openai.com/v1
  chat-model: ${OPENAI_MODEL:gpt-4o-mini}
  timeout: 180s
gemini:
  api-key: ${GEMINI_API_KEY:}
  base-url: https://generativelanguage.googleapis.com/v1beta
  model: ${GEMINI_MODEL:gemini-2.5-flash}
  timeout: 180s

management:
  endpoints:
    web:
      exposure:
        include: health,info





logging:
  level:
    com.hack.app.chat.survey.service.RecommendationService: DEBUG

