spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/hackathon_prod?useSSL=true&serverTimezone=Asia/Seoul}
    username: ${DB_USERNAME:hackathon}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

management:
  endpoint:
    health:
      show-details: when-authorized

server:
  port: ${SERVER_PORT:8080}