version: "3.9"
services:
  nginx:
    build:
      context: ..
      dockerfile: deploy/docker/nginx.Dockerfile
    container_name: hack-nginx-staging
    ports: ["80:80"]
    depends_on:
      - frontend
      - backend
    networks: [hacknet-staging]

  frontend:
    build:
      context: ..
      dockerfile: deploy/docker/frontend.Dockerfile
    container_name: hack-frontend-staging
    networks: [hacknet-staging]

  backend:
    build:
      context: ..
      dockerfile: deploy/docker/backend.Dockerfile
    container_name: hack-backend-staging
    env_file: [deploy/env/.env.prod]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=staging
    expose: ["8080"]
    networks: [hacknet-staging]

networks:
  hacknet-staging:
    driver: bridge