server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:${MYSQL_HOST:localhost}}:${DB_PORT:3306}/${DB_NAME:hackdb}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: ${DB_USER:hackuser}
    password: ${DB_PASS:changeme-please}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
management:
  endpoints:
    web:
      exposure:
        include: health,info

# File Upload Configuration
servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB
    enabled: true

# Static Resources
web:
  resources:
    static-locations: file:/app/uploads/

# CORS Configuration  
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  allow-credentials: true
