server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:${MYSQL_HOST:localhost}}:${DB_PORT:3306}/${DB_NAME:hackdb}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: ${DB_USER:hackuser}
    password: ${DB_PASS:changeme-please}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
management:
  endpoints:
    web:
      exposure:
        include: health,info
