-- 중고등학생을 위한 금융 상식 문장 데이터
DELETE FROM sentence; -- 기존 데이터를 모두 삭제합니다.

INSERT INTO sentence (content) VALUES ('용돈 기입장을 작성하면 돈의 흐름을 파악하고 불필요한 지출을 줄일 수 있어요.');
INSERT INTO sentence (content) VALUES ('저축은 미래를 위해 돈을 모으는 습관으로, 목표를 세우고 꾸준히 실천하는 것이 중요해요.');
INSERT INTO sentence (content) VALUES ('예금은 은행에 돈을 맡기고 이자를 받는 가장 기본적인 저축 방법이에요.');
INSERT INTO sentence (content) VALUES ('적금은 매달 일정 금액을 저축하여 목돈을 만드는 데 유리한 상품이에요.');
INSERT INTO sentence (content) VALUES ('체크카드는 통장에 있는 돈만큼만 사용할 수 있어 과소비를 막는 데 도움이 돼요.');
INSERT INTO sentence (content) VALUES ('신용카드는 미래의 수입을 미리 당겨 쓰는 것이므로, 신중하게 사용해야 해요.');
INSERT INTO sentence (content) VALUES ('할부 구매는 물건 값을 여러 번 나누어 내는 것으로, 이자가 붙을 수 있으니 주의해야 해요.');
INSERT INTO sentence (content) VALUES ('이자율은 돈을 빌리거나 빌려줄 때 붙는 비율로, 높을수록 더 많은 이자를 내거나 받을 수 있어요.');
INSERT INTO sentence (content) VALUES ('복리는 이자에 이자가 붙는 방식으로, 장기 저축 시 원금을 크게 불릴 수 있어요.');
INSERT INTO sentence (content) VALUES ('단리는 원금에만 이자가 붙는 방식으로, 복리보다 수익률이 낮아요.');
INSERT INTO sentence (content) VALUES ('인플레이션은 물가가 오르고 돈의 가치가 떨어지는 현상이에요.');
INSERT INTO sentence (content) VALUES ('디플레이션은 물가가 내리고 돈의 가치가 오르는 현상이에요.');
INSERT INTO sentence (content) VALUES ('주식은 회사의 일부를 소유하는 것으로, 회사가 성장하면 주식 가치도 오를 수 있어요.');
INSERT INTO sentence (content) VALUES ('채권은 국가나 기업에 돈을 빌려주고 이자를 받는 것으로, 주식보다 안정적이에요.');
INSERT INTO sentence (content) VALUES ('펀드는 여러 사람의 돈을 모아 전문가가 대신 투자해주는 상품이에요.');
INSERT INTO sentence (content) VALUES ('분산 투자는 여러 곳에 나누어 투자하여 위험을 줄이는 방법이에요.');
INSERT INTO sentence (content) VALUES ('환율은 다른 나라 돈과의 교환 비율로, 해외여행이나 직구 시 중요해요.');
INSERT INTO sentence (content) VALUES ('세금은 국가나 지방자치단체가 국민에게 거두는 돈으로, 공공 서비스를 위해 사용돼요.');
INSERT INTO sentence (content) VALUES ('소득세는 개인이 벌어들인 소득에 대해 내는 세금이에요.');
INSERT INTO sentence (content) VALUES ('부가가치세는 물건을 사거나 서비스를 이용할 때 가격에 포함되어 내는 세금이에요.');
INSERT INTO sentence (content) VALUES ('연말정산은 1년 동안 낸 세금을 다시 계산하여 더 냈으면 돌려받고 덜 냈으면 더 내는 과정이에요.');
INSERT INTO sentence (content) VALUES ('신용등급은 돈을 빌리고 갚는 능력을 평가하는 점수로, 높을수록 유리해요.');
INSERT INTO sentence (content) VALUES ('대출은 은행이나 금융기관에서 돈을 빌리는 것으로, 이자를 붙여 갚아야 해요.');
INSERT INTO sentence (content) VALUES ('보증은 다른 사람이 돈을 갚지 못할 때 대신 갚아주겠다고 약속하는 것으로, 신중해야 해요.');
INSERT INTO sentence (content) VALUES ('보험은 미래의 위험에 대비하여 미리 돈을 내고 사고 발생 시 보상을 받는 상품이에요.');
INSERT INTO sentence (content) VALUES ('청약통장은 주택을 구매할 때 필요한 저축 상품으로, 꾸준히 납입하는 것이 좋아요.');
INSERT INTO sentence (content) VALUES ('개인형 퇴직연금(IRP)은 노후를 대비하여 스스로 연금을 준비하는 제도예요.');
INSERT INTO sentence (content) VALUES ('금융기관은 은행, 증권사, 보험사 등 돈과 관련된 서비스를 제공하는 곳이에요.');
INSERT INTO sentence (content) VALUES ('은행은 예금, 대출, 환전 등 다양한 금융 서비스를 제공해요.');
INSERT INTO sentence (content) VALUES ('증권사는 주식이나 채권 등 투자 상품을 사고파는 것을 도와줘요.');
INSERT INTO sentence (content) VALUES ('보험사는 질병, 사고 등 위험에 대비하는 보험 상품을 판매해요.');
INSERT INTO sentence (content) VALUES ('저축은행은 일반 은행보다 높은 이자를 주는 예금 상품을 제공하기도 해요.');
INSERT INTO sentence (content) VALUES ('신용협동조합은 조합원들이 돈을 모아 서로 돕는 금융기관이에요.');
INSERT INTO sentence (content) VALUES ('새마을금고는 지역 주민을 위한 금융 서비스를 제공하는 곳이에요.');
INSERT INTO sentence (content) VALUES ('우체국 예금은 국가가 운영하여 안전하게 돈을 맡길 수 있어요.');
INSERT INTO sentence (content) VALUES ('가계부는 수입과 지출을 기록하여 재정 상태를 한눈에 볼 수 있게 해줘요.');
INSERT INTO sentence (content) VALUES ('예산은 일정 기간 동안의 수입과 지출 계획을 세우는 것으로, 현명한 소비의 시작이에요.');
INSERT INTO sentence (content) VALUES ('충동구매는 계획 없이 갑자기 물건을 사는 것으로, 후회할 수 있으니 조심해야 해요.');
INSERT INTO sentence (content) VALUES ('합리적인 소비는 자신의 필요와 예산을 고려하여 가장 만족스러운 선택을 하는 것이에요.');
INSERT INTO sentence (content) VALUES ('절약은 불필요한 지출을 줄이고 아껴 쓰는 습관이에요.');
INSERT INTO sentence (content) VALUES ('투자란 돈을 불리기 위해 자산을 구매하는 것으로, 위험과 수익을 함께 고려해야 해요.');
INSERT INTO sentence (content) VALUES ('원금 손실은 투자한 돈의 일부 또는 전부를 잃는 것을 의미해요.');
INSERT INTO sentence (content) VALUES ('수익률은 투자한 돈 대비 얻은 이익의 비율을 나타내요.');
INSERT INTO sentence (content) VALUES ('배당금은 기업이 이익의 일부를 주주들에게 나누어 주는 돈이에요.');
INSERT INTO sentence (content) VALUES ('시세차익은 주식이나 부동산 가격이 올라서 얻는 이익이에요.');
INSERT INTO sentence (content) VALUES ('주식 시장은 주식을 사고파는 곳으로, 경제 상황에 따라 변동성이 커요.');
INSERT INTO sentence (content) VALUES ('코스피(KOSPI)는 국내 대형 기업들의 주가를 종합한 지수예요.');
INSERT INTO sentence (content) VALUES ('코스닥(KOSDAQ)은 주로 벤처 기업들의 주가를 종합한 지수예요.');
INSERT INTO sentence (content) VALUES ('ETF(상장지수펀드)는 특정 지수를 따라가는 펀드로, 주식처럼 쉽게 사고팔 수 있어요.');
INSERT INTO sentence (content) VALUES ('부동산은 토지나 건물을 의미하며, 장기적인 관점에서 투자 가치가 있어요.');
INSERT INTO sentence (content) VALUES ('전세는 보증금을 맡기고 집을 빌리는 것으로, 월세보다 주거비 부담이 적을 수 있어요.');
INSERT INTO sentence (content) VALUES ('월세는 매달 일정 금액을 내고 집을 빌리는 것으로, 보증금 부담이 적어요.');
INSERT INTO sentence (content) VALUES ('모기지론은 주택을 담보로 돈을 빌리는 대출 상품이에요.');
INSERT INTO sentence (content) VALUES ('학자금 대출은 학비를 마련하기 위해 빌리는 돈으로, 졸업 후 갚아야 해요.');
INSERT INTO sentence (content) VALUES ('신용불량자는 돈을 제때 갚지 못해 신용도가 매우 낮아진 사람을 의미해요.');
INSERT INTO sentence (content) VALUES ('파산은 빚을 갚을 능력이 없을 때 법원의 도움을 받아 채무를 정리하는 제도예요.');
INSERT INTO sentence (content) VALUES ('개인회생은 빚을 갚기 어려운 사람이 법원의 도움을 받아 일정 기간 동안 빚을 나누어 갚는 제도예요.');
INSERT INTO sentence (content) VALUES ('금융사기는 돈을 가로채기 위해 거짓말이나 속임수를 쓰는 범죄예요.');
INSERT INTO sentence (content) VALUES ('보이스피싱은 전화로 속여 돈을 빼앗는 사기 수법이에요.');
INSERT INTO sentence (content) VALUES ('스미싱은 문자 메시지로 속여 개인 정보를 빼앗거나 돈을 가로채는 사기 수법이에요.');
INSERT INTO sentence (content) VALUES ('피싱은 이메일이나 웹사이트로 속여 개인 정보를 빼앗는 사기 수법이에요.');
INSERT INTO sentence (content) VALUES ('금융감독원은 금융 소비자를 보호하고 금융 시장을 감독하는 기관이에요.');
INSERT INTO sentence (content) VALUES ('한국은행은 우리나라의 물가와 금융 안정을 책임지는 중앙은행이에요.');
INSERT INTO sentence (content) VALUES ('기획재정부는 국가의 경제 정책과 예산을 담당하는 정부 부처예요.');
INSERT INTO sentence (content) VALUES ('국세청은 세금을 거두는 일을 담당하는 정부 기관이에요.');
INSERT INTO sentence (content) VALUES ('예금자보호법은 은행이 망해도 예금의 일부를 돌려받을 수 있도록 보호해주는 법이에요.');
INSERT INTO sentence (content) VALUES ('재테크는 돈을 효율적으로 관리하고 불리는 기술을 의미해요.');
INSERT INTO sentence (content) VALUES ('목돈 마련은 큰 돈을 모으는 것으로, 주택 구매나 결혼 등 큰 목표를 위해 필요해요.');
INSERT INTO sentence (content) VALUES ('노후 대비는 은퇴 후의 삶을 위해 미리 돈을 준비하는 것이에요.');
INSERT INTO sentence (content) VALUES ('비상금은 예상치 못한 지출에 대비하여 따로 모아두는 돈이에요.');
INSERT INTO sentence (content) VALUES ('용돈은 부모님이나 다른 사람에게서 받는 생활비예요.');
INSERT INTO sentence (content) VALUES ('아르바이트는 학업 외에 돈을 벌기 위해 하는 단기 일자리예요.');
INSERT INTO sentence (content) VALUES ('최저임금은 법으로 정해진 가장 낮은 시급으로, 모든 근로자는 이 이상을 받아야 해요.');
INSERT INTO sentence (content) VALUES ('근로계약서는 일의 조건과 급여 등을 명시한 계약서로, 꼭 작성해야 해요.');
INSERT INTO sentence (content) VALUES ('주휴수당은 주 15시간 이상 일한 근로자에게 유급 주휴일을 주는 제도예요.');
INSERT INTO sentence (content) VALUES ('퇴직금은 1년 이상 일한 근로자가 퇴직할 때 받는 돈이에요.');
INSERT INTO sentence (content) VALUES ('4대 보험은 국민연금, 건강보험, 고용보험, 산재보험으로 구성된 사회보험이에요.');
INSERT INTO sentence (content) VALUES ('국민연금은 노후에 연금을 받을 수 있도록 미리 납부하는 보험이에요.');
INSERT INTO sentence (content) VALUES ('건강보험은 질병이나 부상 시 병원비를 지원해주는 보험이에요.');
INSERT INTO sentence (content) VALUES ('고용보험은 실업 시 실업급여를 지급하고 재취업을 돕는 보험이에요.');
INSERT INTO sentence (content) VALUES ('산재보험은 업무 중 다치거나 질병에 걸렸을 때 보상해주는 보험이에요.');
INSERT INTO sentence (content) VALUES ('신용카드 포인트는 신용카드 사용 금액에 따라 적립되는 점수로, 현금처럼 사용할 수 있어요.');
INSERT INTO sentence (content) VALUES ('마일리지(항공)는 항공사 이용 실적에 따라 적립되는 점수로, 항공권 구매 등에 사용할 수 있어요.');
INSERT INTO sentence (content) VALUES ('할인 혜택은 물건이나 서비스를 더 저렴하게 구매할 수 있는 기회예요.');
INSERT INTO sentence (content) VALUES ('쿠폰은 특정 상품이나 서비스에 대해 할인이나 추가 혜택을 받을 수 있는 증서예요.');
INSERT INTO sentence (content) VALUES ('기프티콘은 모바일로 주고받는 상품권으로, 실제 물건이나 서비스로 교환할 수 있어요.');
INSERT INTO sentence (content) VALUES ('중고거래는 사용하던 물건을 다른 사람에게 팔거나 사는 것으로, 자원 낭비를 줄일 수 있어요.');
INSERT INTO sentence (content) VALUES ('렌탈 서비스는 물건을 구매하는 대신 빌려 쓰는 것으로, 초기 비용 부담을 줄일 수 있어요.');
INSERT INTO sentence (content) VALUES ('구독 서비스는 매달 일정 금액을 내고 콘텐츠나 서비스를 계속 이용하는 것이에요.');
INSERT INTO sentence (content) VALUES ('공유 경제는 물건이나 공간을 여러 사람이 함께 사용하는 경제 활동이에요.');
INSERT INTO sentence (content) VALUES ('가성비는 가격 대비 성능이 좋은 것을 의미해요.');
INSERT INTO sentence (content) VALUES ('가심비는 가격 대비 마음의 만족도가 높은 것을 의미해요.');
INSERT INTO sentence (content) VALUES ('욜로(YOLO)는 한 번뿐인 인생을 즐기며 현재의 행복을 추구하는 삶의 방식이에요.');
INSERT INTO sentence (content) VALUES ('파이어족은 경제적 자유를 얻어 조기에 은퇴하는 것을 목표로 하는 사람들을 의미해요.');
INSERT INTO sentence (content) VALUES ('N잡러는 여러 가지 일을 동시에 하여 수입을 다각화하는 사람들을 의미해요.');
INSERT INTO sentence (content) VALUES ('재무 목표는 돈과 관련된 구체적인 목표로, 단기, 중기, 장기로 나누어 세울 수 있어요.');
INSERT INTO sentence (content) VALUES ('재무 계획은 재무 목표를 달성하기 위한 구체적인 실천 방안이에요.');
INSERT INTO sentence (content) VALUES ('자산은 내가 가지고 있는 모든 재산으로, 현금, 예금, 주식, 부동산 등이 있어요.');
INSERT INTO sentence (content) VALUES ('부채는 내가 갚아야 할 빚으로, 대출금, 카드 할부금 등이 있어요.');
INSERT INTO sentence (content) VALUES ('순자산은 자산에서 부채를 뺀 것으로, 나의 실제 재산 규모를 나타내요.');
INSERT INTO sentence (content) VALUES ('수입은 내가 벌어들이는 돈으로, 월급, 용돈, 아르바이트 수입 등이 있어요.');
INSERT INTO sentence (content) VALUES ('지출은 내가 사용하는 돈으로, 식비, 교통비, 통신비 등이 있어요.');
INSERT INTO sentence (content) VALUES ('고정 지출은 매달 일정하게 나가는 돈으로, 통신비, 교통비 등이 있어요.');
INSERT INTO sentence (content) VALUES ('변동 지출은 매달 금액이 달라지는 돈으로, 식비, 문화생활비 등이 있어요.');
INSERT INTO sentence (content) VALUES ('비상금 통장은 예상치 못한 지출에 대비하여 돈을 모아두는 통장이에요.');
INSERT INTO sentence (content) VALUES ('자동이체는 매달 정해진 날짜에 자동으로 돈이 빠져나가도록 설정하는 기능이에요.');
INSERT INTO sentence (content) VALUES ('금융 상품은 돈을 관리하고 불리는 데 도움이 되는 다양한 상품들을 의미해요.');
INSERT INTO sentence (content) VALUES ('금융 문맹은 금융 지식이 부족하여 돈을 제대로 관리하지 못하는 상태를 의미해요.');
INSERT INTO sentence (content) VALUES ('금융 지식은 돈을 현명하게 관리하고 투자하는 데 필요한 정보와 능력이에요.');
INSERT INTO sentence (content) VALUES ('경제 신문이나 뉴스를 읽으면 경제 흐름을 이해하는 데 도움이 돼요.');
INSERT INTO sentence (content) VALUES ('경제 용어를 익히면 금융 관련 정보를 더 쉽게 이해할 수 있어요.');
INSERT INTO sentence (content) VALUES ('금융 교육은 돈을 현명하게 관리하는 방법을 배우는 과정이에요.');
INSERT INTO sentence (content) VALUES ('어릴 때부터 올바른 경제 습관을 기르는 것이 중요해요.');
INSERT INTO sentence (content) VALUES ('부모님과 돈에 대해 이야기하는 것은 좋은 경제 교육 방법이에요.');
INSERT INTO sentence (content) VALUES ('친구들과 돈에 대한 정보를 공유하는 것도 도움이 될 수 있어요.');
INSERT INTO sentence (content) VALUES ('궁금한 금융 정보는 전문가나 신뢰할 수 있는 기관에 문의하는 것이 좋아요.');
INSERT INTO sentence (content) VALUES ('돈은 목적을 달성하기 위한 수단이지, 그 자체가 목적이 될 수 없어요.');
INSERT INTO sentence (content) VALUES ('돈을 현명하게 사용하면 더 풍요로운 삶을 살 수 있어요.');
INSERT INTO sentence (content) VALUES ('돈을 아끼고 저축하는 습관은 미래를 위한 든든한 기반이 돼요.');
INSERT INTO sentence (content) VALUES ('투자는 신중하게 공부하고 자신에게 맞는 방법을 찾아야 해요.');
INSERT INTO sentence (content) VALUES ('빚은 꼭 필요한 경우에만 지고, 계획적으로 갚아나가야 해요.');
INSERT INTO sentence (content) VALUES ('금융 사기는 항상 조심하고 의심스러운 제안은 거절해야 해요.');
INSERT INTO sentence (content) VALUES ('자신의 소득과 지출을 정확히 파악하는 것이 재정 관리의 첫걸음이에요.');
INSERT INTO sentence (content) VALUES ('재무 목표를 세우고 꾸준히 노력하면 꿈을 이룰 수 있어요.');
INSERT INTO sentence (content) VALUES ('돈은 행복을 위한 도구이며, 균형 잡힌 삶을 위해 사용해야 해요.');
INSERT INTO sentence (content) VALUES ('금융 지식은 어른이 되어서도 계속해서 배우고 발전시켜야 할 중요한 능력이에요.');
INSERT INTO sentence (content) VALUES ('경제적 자유는 돈으로부터의 해방을 의미하며, 많은 사람들의 목표예요.');
INSERT INTO sentence (content) VALUES ('자신만의 투자 원칙을 세우고 흔들리지 않는 것이 중요해요.');
INSERT INTO sentence (content) VALUES ('위험을 감수할 수 있는 정도를 파악하고 투자해야 해요.');
INSERT INTO sentence (content) VALUES ('장기적인 관점에서 투자하는 것이 단기적인 변동성에 흔들리지 않는 방법이에요.');
INSERT INTO sentence (content) VALUES ('다양한 금융 상품의 특징을 이해하고 자신에게 맞는 것을 선택해야 해요.');
INSERT INTO sentence (content) VALUES ('금융 시장의 변화에 관심을 가지고 꾸준히 학습해야 해요.');
INSERT INTO sentence (content) VALUES ('자신의 소비 습관을 분석하고 개선하는 노력이 필요해요.');
INSERT INTO sentence (content) VALUES ('돈을 빌려줄 때는 신중하게 생각하고, 돌려받지 못할 수도 있다는 점을 인지해야 해요.');
INSERT INTO sentence (content) VALUES ('돈을 빌릴 때는 상환 계획을 철저히 세우고 감당할 수 있는 범위 내에서 빌려야 해요.');
INSERT INTO sentence (content) VALUES ('신용 점수는 한 번 나빠지면 회복하기 어려우니 꾸준히 관리해야 해요.');
INSERT INTO sentence (content) VALUES ('개인 정보는 소중하므로 함부로 알려주거나 유출되지 않도록 주의해야 해요.');
INSERT INTO sentence (content) VALUES ('금융 상품 가입 시에는 약관을 꼼꼼히 읽고 이해해야 해요.');
INSERT INTO sentence (content) VALUES ('불확실한 정보에 현혹되지 않고 사실을 확인하는 습관을 길러야 해요.');
INSERT INTO sentence (content) VALUES ('자신의 재정 상황을 주기적으로 점검하고 필요에 따라 계획을 수정해야 해요.');
INSERT INTO sentence (content) VALUES ('경제 용어는 어렵게 느껴질 수 있지만, 꾸준히 공부하면 익숙해질 수 있어요.');
INSERT INTO sentence (content) VALUES ('금융 지식은 학교 공부만큼이나 중요한 삶의 기술이에요.');
INSERT INTO sentence (content) VALUES ('돈에 대한 긍정적인 태도를 가지고 현명하게 다루는 방법을 배워야 해요.');
INSERT INTO sentence (content) VALUES ('자신만의 재정 원칙을 세우고 지켜나가는 것이 중요해요.');
INSERT INTO sentence (content) VALUES ('경제적 어려움이 생겼을 때는 혼자 고민하지 말고 전문가의 도움을 받는 것이 좋아요.');
INSERT INTO sentence (content) VALUES ('돈은 도구일 뿐, 진정한 행복은 돈으로 살 수 없는 가치에 있다는 것을 기억해요.');
INSERT INTO sentence (content) VALUES ('현명한 금융 생활은 건강하고 행복한 삶을 위한 필수 요소예요.');
INSERT INTO sentence (content) VALUES ('금융 상식을 꾸준히 학습하여 경제적 자립을 이루는 멋진 어른이 되세요!');