-- 사회초년생을 위한 금융 상식 문장 데이터 (용어 정의 및 정보 위주)
DELETE FROM sentence; -- 기존 데이터를 모두 삭제합니다.

INSERT INTO sentence (content) VALUES ('월급은 근로의 대가로 매월 지급되는 급여를 의미합니다.');
INSERT INTO sentence (content) VALUES ('비상금은 예상치 못한 지출에 대비하여 따로 모아두는 돈을 말합니다.');
INSERT INTO sentence (content) VALUES ('신용카드는 신용을 담보로 물품을 구매하거나 서비스를 이용할 수 있는 카드입니다.');
INSERT INTO sentence (content) VALUES ('체크카드는 은행 계좌 잔액 범위 내에서만 사용할 수 있는 카드입니다.');
INSERT INTO sentence (content) VALUES ('신용등급은 개인의 신용도를 평가하는 점수로, 금융 거래에 영향을 미칩니다.');
INSERT INTO sentence (content) VALUES ('주택청약종합저축은 주택 구입을 위한 목돈 마련과 청약 자격을 얻기 위한 저축 상품입니다.');
INSERT INTO sentence (content) VALUES ('개인형 퇴직연금(IRP)은 근로자가 퇴직금을 직접 운용하고 노후 자금을 준비하는 제도입니다.');
INSERT INTO sentence (content) VALUES ('연말정산은 1년 동안 납부한 세금을 정산하여 환급받거나 추가 납부하는 과정입니다.');
INSERT INTO sentence (content) VALUES ('소득공제는 과세 대상 소득에서 일정 금액을 공제하여 세금을 줄여주는 제도입니다.');
INSERT INTO sentence (content) VALUES ('세액공제는 산출된 세액에서 일정 금액을 직접 공제하여 세금을 줄여주는 제도입니다.');
INSERT INTO sentence (content) VALUES ('급여명세서는 급여 내역, 공제 항목, 실수령액 등이 기재된 문서입니다.');
INSERT INTO sentence (content) VALUES ('재무 목표는 돈과 관련된 구체적인 목표로, 주택 구매, 은퇴 자금 마련 등이 있습니다.');
INSERT INTO sentence (content) VALUES ('가계부는 수입과 지출을 기록하여 재정 상태를 파악하는 도구입니다.');
INSERT INTO sentence (content) VALUES ('예산은 일정 기간 동안의 수입과 지출 계획을 미리 세우는 것을 의미합니다.');
INSERT INTO sentence (content) VALUES ('고정 지출은 매달 일정하게 발생하는 지출로, 통신비, 월세 등이 있습니다.');
INSERT INTO sentence (content) VALUES ('변동 지출은 매달 금액이 달라지는 지출로, 식비, 문화생활비 등이 있습니다.');
INSERT INTO sentence (content) VALUES ('짠테크는 절약을 통해 돈을 모으는 재테크 방법을 통칭합니다.');
INSERT INTO sentence (content) VALUES ('앱테크는 스마트폰 앱을 활용하여 포인트를 쌓거나 돈을 버는 활동입니다.');
INSERT INTO sentence (content) VALUES ('투자는 자산을 구매하여 미래의 수익을 기대하는 행위입니다.');
INSERT INTO sentence (content) VALUES ('원금 손실은 투자한 금액의 일부 또는 전부를 잃는 것을 의미합니다.');
INSERT INTO sentence (content) VALUES ('주식은 기업의 소유권을 나타내는 증권으로, 주식 시장에서 거래됩니다.');
INSERT INTO sentence (content) VALUES ('펀드는 여러 투자자의 돈을 모아 전문가가 대신 투자하는 금융 상품입니다.');
INSERT INTO sentence (content) VALUES ('ETF(상장지수펀드)는 특정 지수를 추종하며 주식처럼 거래되는 펀드입니다.');
INSERT INTO sentence (content) VALUES ('부동산은 토지 및 그 정착물을 의미하며, 주택, 상가, 토지 등이 있습니다.');
INSERT INTO sentence (content) VALUES ('전세는 보증금을 맡기고 주택을 빌리는 임대차 계약 방식입니다.');
INSERT INTO sentence (content) VALUES ('월세는 매달 일정 금액의 임대료를 지불하고 주택을 빌리는 방식입니다.');
INSERT INTO sentence (content) VALUES ('대출은 금융기관으로부터 돈을 빌리는 행위로, 이자를 붙여 상환해야 합니다.');
INSERT INTO sentence (content) VALUES ('전세자금대출은 전세 보증금 마련을 위해 은행에서 빌리는 돈입니다.');
INSERT INTO sentence (content) VALUES ('주택담보대출은 주택을 담보로 제공하고 빌리는 대출 상품입니다.');
INSERT INTO sentence (content) VALUES ('신용대출은 담보 없이 개인의 신용을 바탕으로 빌리는 대출입니다.');
INSERT INTO sentence (content) VALUES ('보험은 미래의 불확실한 위험에 대비하여 경제적 손실을 보장하는 상품입니다.');
INSERT INTO sentence (content) VALUES ('실손보험은 질병이나 상해로 인한 의료비를 보장해주는 보험입니다.');
INSERT INTO sentence (content) VALUES ('종신보험은 피보험자가 사망 시 유족에게 보험금을 지급하는 보험입니다.');
INSERT INTO sentence (content) VALUES ('연금보험은 노후 생활 자금을 마련하기 위한 저축성 보험입니다.');
INSERT INTO sentence (content) VALUES ('금융사기는 거짓이나 속임수로 타인의 재산을 편취하는 범죄를 말합니다.');
INSERT INTO sentence (content) VALUES ('보이스피싱은 전화를 통해 개인 정보를 탈취하거나 금전을 요구하는 사기 수법입니다.');
INSERT INTO sentence (content) VALUES ('스미싱은 문자 메시지를 이용해 악성 앱 설치를 유도하거나 개인 정보를 탈취하는 사기입니다.');
INSERT INTO sentence (content) VALUES ('피싱은 이메일이나 웹사이트를 통해 개인 정보를 탈취하는 사기 수법입니다.');
INSERT INTO sentence (content) VALUES ('금융감독원은 금융 소비자를 보호하고 금융 시장을 감독하는 기관입니다.');
INSERT INTO sentence (content) VALUES ('한국은행은 물가 안정과 금융 시스템 안정을 책임지는 중앙은행입니다.');
INSERT INTO sentence (content) VALUES ('예금자보호법은 금융기관 파산 시 예금자의 예금을 보호하는 법률입니다.');
INSERT INTO sentence (content) VALUES ('재테크는 재산을 효율적으로 관리하고 증식시키는 방법을 의미합니다.');
INSERT INTO sentence (content) VALUES ('목돈 마련은 큰 금액의 돈을 모으는 것으로, 특정 목표 달성을 위해 필요합니다.');
INSERT INTO sentence (content) VALUES ('노후 대비는 은퇴 후의 안정적인 생활을 위해 자금을 준비하는 것입니다.');
INSERT INTO sentence (content) VALUES ('소비는 재화나 서비스를 구매하여 사용하는 행위를 말합니다.');
INSERT INTO sentence (content) VALUES ('저축은 현재의 소비를 줄이고 미래를 위해 돈을 모으는 행위입니다.');
INSERT INTO sentence (content) VALUES ('이자율은 돈을 빌리거나 빌려줄 때 적용되는 비율을 의미합니다.');
INSERT INTO sentence (content) VALUES ('복리는 이자에 이자가 붙는 방식으로, 장기 투자 시 효과가 큽니다.');
INSERT INTO sentence (content) VALUES ('단리는 원금에만 이자가 붙는 방식으로, 복리보다 수익률이 낮습니다.');
INSERT INTO sentence (content) VALUES ('인플레이션은 물가가 지속적으로 상승하고 화폐 가치가 하락하는 현상입니다.');
INSERT INTO sentence (content) VALUES ('디플레이션은 물가가 지속적으로 하락하고 화폐 가치가 상승하는 현상입니다.');
INSERT INTO sentence (content) VALUES ('환율은 한 국가의 통화와 다른 국가의 통화 간의 교환 비율을 말합니다.');
INSERT INTO sentence (content) VALUES ('세금은 국가나 지방자치단체가 국민으로부터 강제로 징수하는 돈입니다.');
INSERT INTO sentence (content) VALUES ('소득세는 개인이 얻은 소득에 대해 부과되는 세금입니다.');
INSERT INTO sentence (content) VALUES ('부가가치세는 상품이나 서비스에 붙는 세금으로, 소비자가 부담합니다.');
INSERT INTO sentence (content) VALUES ('신용점수는 개인의 신용도를 수치화한 것으로, 대출 금리 등에 영향을 줍니다.');
INSERT INTO sentence (content) VALUES ('파산은 채무자가 빚을 갚을 능력이 없을 때 법원의 도움을 받아 채무를 정리하는 제도입니다.');
INSERT INTO sentence (content) VALUES ('개인회생은 채무자가 법원의 인가를 받아 일정 기간 동안 빚을 나누어 갚는 제도입니다.');
INSERT INTO sentence (content) VALUES ('금융기관은 은행, 증권사, 보험사 등 금융 서비스를 제공하는 회사입니다.');
INSERT INTO sentence (content) VALUES ('은행은 예금, 대출, 환전 등 다양한 금융 업무를 취급합니다.');
INSERT INTO sentence (content) VALUES ('증권사는 주식, 채권 등 유가증권의 매매를 중개하는 회사입니다.');
INSERT INTO sentence (content) VALUES ('보험사는 보험 상품을 판매하고 보험금을 지급하는 회사입니다.');
INSERT INTO sentence (content) VALUES ('저축은행은 일반 은행보다 높은 금리의 예금 상품을 제공하기도 합니다.');
INSERT INTO sentence (content) VALUES ('신용협동조합은 조합원들의 상호 협동을 통해 금융 서비스를 제공하는 비영리 금융기관입니다.');
INSERT INTO sentence (content) VALUES ('새마을금고는 지역 주민을 위한 금융 서비스를 제공하는 상호금융기관입니다.');
INSERT INTO sentence (content) VALUES ('우체국 예금은 국가가 운영하여 안정성이 높은 예금 상품입니다.');
INSERT INTO sentence (content) VALUES ('가성비는 가격 대비 성능이 좋은 것을 의미하는 경제 용어입니다.');
INSERT INTO sentence (content) VALUES ('가심비는 가격 대비 심리적 만족도가 높은 것을 의미하는 신조어입니다.');
INSERT INTO sentence (content) VALUES ('욜로(YOLO)는 현재의 행복을 중시하며 삶을 즐기는 소비 태도를 말합니다.');
INSERT INTO sentence (content) VALUES ('파이어족은 경제적 자유를 달성하여 조기에 은퇴하는 것을 목표로 하는 사람들을 지칭합니다.');
INSERT INTO sentence (content) VALUES ('N잡러는 여러 직업을 동시에 가지며 수입원을 다각화하는 사람을 의미합니다.');
INSERT INTO sentence (content) VALUES ('자산은 개인이 소유한 모든 재산으로, 현금, 예금, 주식, 부동산 등이 포함됩니다.');
INSERT INTO sentence (content) VALUES ('부채는 개인이 갚아야 할 빚으로, 대출금, 카드 할부금 등이 해당됩니다.');
INSERT INTO sentence (content) VALUES ('순자산은 총 자산에서 총 부채를 제외한 금액으로, 개인의 실질적인 재산 규모를 나타냅니다.');
INSERT INTO sentence (content) VALUES ('수입은 개인이 벌어들이는 돈으로, 월급, 용돈, 사업 소득 등이 있습니다.');
INSERT INTO sentence (content) VALUES ('지출은 개인이 사용하는 돈으로, 식비, 교통비, 통신비 등이 포함됩니다.');
INSERT INTO sentence (content) VALUES ('비상금 통장은 예상치 못한 지출에 대비하여 자금을 보관하는 별도의 계좌입니다.');
INSERT INTO sentence (content) VALUES ('자동이체는 정해진 날짜에 특정 계좌에서 다른 계좌로 자동으로 돈이 이체되는 서비스입니다.');
INSERT INTO sentence (content) VALUES ('금융 상품은 돈을 관리하고 불리는 데 활용되는 다양한 형태의 상품을 말합니다.');
INSERT INTO sentence (content) VALUES ('금융 문맹은 금융 지식이 부족하여 합리적인 금융 의사결정을 하기 어려운 상태를 의미합니다.');
INSERT INTO sentence (content) VALUES ('금융 지식은 돈을 현명하게 관리하고 투자하는 데 필요한 정보와 능력을 말합니다.');
INSERT INTO sentence (content) VALUES ('경제 신문은 경제 관련 뉴스, 분석, 통계 등을 제공하는 신문입니다.');
INSERT INTO sentence (content) VALUES ('경제 용어는 경제 활동과 관련된 전문적인 용어를 의미합니다.');
INSERT INTO sentence (content) VALUES ('금융 교육은 금융 지식과 기술을 습득하여 합리적인 금융 생활을 돕는 교육입니다.');
INSERT INTO sentence (content) VALUES ('근로계약서는 근로자와 사용자 간의 근로 조건을 명시한 계약 문서입니다.');
INSERT INTO sentence (content) VALUES ('최저임금은 법으로 정해진 근로자가 받을 수 있는 최소한의 시급 또는 월급입니다.');
INSERT INTO sentence (content) VALUES ('주휴수당은 주 15시간 이상 근무한 근로자에게 유급 주휴일에 지급되는 수당입니다.');
INSERT INTO sentence (content) VALUES ('퇴직금은 1년 이상 근무한 근로자가 퇴직 시 받는 일시금입니다.');
INSERT INTO sentence (content) VALUES ('4대 보험은 국민연금, 건강보험, 고용보험, 산재보험을 통칭하는 사회보험입니다.');
INSERT INTO sentence (content) VALUES ('국민연금은 노령, 장애, 사망 시 연금을 지급하여 국민의 생활 안정을 돕는 제도입니다.');
INSERT INTO sentence (content) VALUES ('건강보험은 질병이나 부상으로 인한 의료비 부담을 덜어주는 사회보험입니다.');
INSERT INTO sentence (content) VALUES ('고용보험은 실업 시 실업급여를 지급하고 재취업을 지원하는 사회보험입니다.');
INSERT INTO sentence (content) VALUES ('산재보험은 업무상 재해를 당한 근로자에게 보상하는 사회보험입니다.');
INSERT INTO sentence (content) VALUES ('신용카드 포인트는 신용카드 사용 금액에 따라 적립되는 점수로, 현금처럼 사용할 수 있습니다.');
INSERT INTO sentence (content) VALUES ('마일리지(항공)는 항공사 이용 실적에 따라 적립되는 점수로, 항공권 구매 등에 활용됩니다.');
INSERT INTO sentence (content) VALUES ('할인 혜택은 상품이나 서비스를 정가보다 저렴하게 구매할 수 있는 기회입니다.');
INSERT INTO sentence (content) VALUES ('쿠폰은 특정 상품이나 서비스에 대해 할인이나 추가 혜택을 제공하는 증서입니다.');
INSERT INTO sentence (content) VALUES ('기프티콘은 모바일로 주고받는 상품권으로, 실제 상품이나 서비스로 교환 가능합니다.');
INSERT INTO sentence (content) VALUES ('중고거래는 사용하던 물건을 다른 사람에게 팔거나 사는 거래 방식입니다.');
INSERT INTO sentence (content) VALUES ('렌탈 서비스는 물건을 구매하는 대신 빌려 쓰는 것으로, 초기 비용 부담을 줄일 수 있습니다.');
INSERT INTO sentence (content) VALUES ('구독 서비스는 매달 일정 금액을 내고 콘텐츠나 서비스를 지속적으로 이용하는 방식입니다.');
INSERT INTO sentence (content) VALUES ('공유 경제는 물건, 공간, 서비스를 여러 사람이 함께 사용하는 경제 활동입니다.');
INSERT INTO sentence (content) VALUES ('재무 상담은 재무 전문가로부터 개인의 재정 상태에 대한 조언을 받는 것입니다.');
INSERT INTO sentence (content) VALUES ('투자 원칙은 투자를 할 때 지켜야 할 자신만의 기준과 규칙을 말합니다.');
INSERT INTO sentence (content) VALUES ('위험 감수 성향은 투자를 통해 손실을 볼 가능성을 얼마나 받아들일 수 있는지를 나타냅니다.');
INSERT INTO sentence (content) VALUES ('장기 투자는 단기적인 시장 변동에 흔들리지 않고 장기적인 관점에서 투자하는 전략입니다.');
INSERT INTO sentence (content) VALUES ('분산 투자는 여러 자산에 나누어 투자하여 위험을 줄이는 투자 전략입니다.');
INSERT INTO sentence (content) VALUES ('금융 시장은 금융 상품이 거래되는 시장으로, 주식 시장, 채권 시장 등이 있습니다.');
INSERT INTO sentence (content) VALUES ('소비 습관은 개인이 돈을 쓰고 저축하는 방식이나 경향을 의미합니다.');
INSERT INTO sentence (content) VALUES ('개인 정보는 개인을 식별할 수 있는 정보로, 이름, 주민등록번호, 연락처 등이 있습니다.');
INSERT INTO sentence (content) VALUES ('약관은 계약의 내용을 상세하게 규정한 조항들을 말합니다.');
INSERT INTO sentence (content) VALUES ('재정 상황은 개인의 수입, 지출, 자산, 부채 등을 포함한 전반적인 경제 상태를 의미합니다.');
INSERT INTO sentence (content) VALUES ('경제적 자립은 스스로의 힘으로 경제 생활을 영위하는 것을 의미합니다.');
INSERT INTO sentence (content) VALUES ('경제적 자유는 돈으로부터의 구속에서 벗어나 원하는 삶을 살 수 있는 상태를 말합니다.');
INSERT INTO sentence (content) VALUES ('금융 상품은 돈을 관리하고 불리는 데 도움이 되는 다양한 상품들을 의미해요.');
INSERT INTO sentence (content) VALUES ('금융 문맹은 금융 지식이 부족하여 돈을 제대로 관리하지 못하는 상태를 의미해요.');
INSERT INTO sentence (content) VALUES ('금융 지식은 돈을 현명하게 관리하고 투자하는 데 필요한 정보와 능력이에요.');
INSERT INTO sentence (content) VALUES ('경제 신문이나 뉴스를 읽으면 경제 흐름을 이해하는 데 도움이 돼요.');
INSERT INTO sentence (content) VALUES ('경제 용어를 익히면 금융 관련 정보를 더 쉽게 이해할 수 있어요.');
INSERT INTO sentence (content) VALUES ('금융 교육은 돈을 현명하게 관리하는 방법을 배우는 과정이에요.');
INSERT INTO sentence (content) VALUES ('어릴 때부터 올바른 경제 습관을 기르는 것이 중요해요.');
INSERT INTO sentence (content) VALUES ('부모님과 돈에 대해 이야기하는 것은 좋은 경제 교육 방법이에요.');
INSERT INTO sentence (content) VALUES ('친구들과 돈에 대한 정보를 공유하는 것도 도움이 될 수 있어요.');
INSERT INTO sentence (content) VALUES ('궁금한 금융 정보는 전문가나 신뢰할 수 있는 기관에 문의하는 것이 좋아요.');
INSERT INTO sentence (content) VALUES ('돈은 목적을 달성하기 위한 수단이지, 그 자체가 목적이 될 수 없어요.');
INSERT INTO sentence (content) VALUES ('돈을 현명하게 사용하면 더 풍요로운 삶을 살 수 있어요.');
INSERT INTO sentence (content) VALUES ('돈을 아끼고 저축하는 습관은 미래를 위한 든든한 기반이 돼요.');
INSERT INTO sentence (content) VALUES ('투자는 신중하게 공부하고 자신에게 맞는 방법을 찾아야 해요.');
INSERT INTO sentence (content) VALUES ('빚은 꼭 필요한 경우에만 지고, 계획적으로 갚아나가야 해요.');
INSERT INTO sentence (content) VALUES ('금융 사기는 항상 조심하고 의심스러운 제안은 거절해야 해요.');
INSERT INTO sentence (content) VALUES ('자신의 소득과 지출을 정확히 파악하는 것이 재정 관리의 첫걸음이에요.');
INSERT INTO sentence (content) VALUES ('재무 목표를 세우고 꾸준히 노력하면 꿈을 이룰 수 있어요.');
INSERT INTO sentence (content) VALUES ('돈은 행복을 위한 도구이며, 균형 잡힌 삶을 위해 사용해야 해요.');
INSERT INTO sentence (content) VALUES ('금융 지식은 어른이 되어서도 계속해서 배우고 발전시켜야 할 중요한 능력이에요.');
INSERT INTO sentence (content) VALUES ('경제적 자유는 돈으로부터의 해방을 의미하며, 많은 사람들의 목표예요.');
INSERT INTO sentence (content) VALUES ('자신만의 투자 원칙을 세우고 흔들리지 않는 것이 중요해요.');
INSERT INTO sentence (content) VALUES ('위험을 감수할 수 있는 정도를 파악하고 투자해야 해요.');
INSERT INTO sentence (content) VALUES ('장기적인 관점에서 투자하는 것이 단기적인 변동성에 흔들리지 않는 방법이에요.');
INSERT INTO sentence (content) VALUES ('다양한 금융 상품의 특징을 이해하고 자신에게 맞는 것을 선택해야 해요.');
INSERT INTO sentence (content) VALUES ('금융 시장의 변화에 관심을 가지고 꾸준히 학습해야 해요.');
INSERT INTO sentence (content) VALUES ('자신의 소비 습관을 분석하고 개선하는 노력이 필요해요.');
INSERT INTO sentence (content) VALUES ('돈을 빌려줄 때는 신중하게 생각하고, 돌려받지 못할 수도 있다는 점을 인지해야 해요.');
INSERT INTO sentence (content) VALUES ('돈을 빌릴 때는 상환 계획을 철저히 세우고 감당할 수 있는 범위 내에서 빌려야 해요.');
INSERT INTO sentence (content) VALUES ('신용 점수는 한 번 나빠지면 회복하기 어려우니 꾸준히 관리해야 해요.');
INSERT INTO sentence (content) VALUES ('개인 정보는 소중하므로 함부로 알려주거나 유출되지 않도록 주의해야 해요.');
INSERT INTO sentence (content) VALUES ('금융 상품 가입 시에는 약관을 꼼꼼히 읽고 이해해야 해요.');
INSERT INTO sentence (content) VALUES ('불확실한 정보에 현혹되지 않고 사실을 확인하는 습관을 길러야 해요.');
INSERT INTO sentence (content) VALUES ('자신의 재정 상황을 주기적으로 점검하고 필요에 따라 계획을 수정해야 해요.');
INSERT INTO sentence (content) VALUES ('경제 용어는 어렵게 느껴질 수 있지만, 꾸준히 공부하면 익숙해질 수 있어요.');
INSERT INTO sentence (content) VALUES ('금융 지식은 학교 공부만큼이나 중요한 삶의 기술이에요.');
INSERT INTO sentence (content) VALUES ('돈에 대한 긍정적인 태도를 가지고 현명하게 다루는 방법을 배워야 해요.');
INSERT INTO sentence (content) VALUES ('자신만의 재정 원칙을 세우고 지켜나가는 것이 중요해요.');
INSERT INTO sentence (content) VALUES ('경제적 어려움이 생겼을 때는 혼자 고민하지 말고 전문가의 도움을 받는 것이 좋아요.');
INSERT INTO sentence (content) VALUES ('돈은 도구일 뿐, 진정한 행복은 돈으로 살 수 없는 가치에 있다는 것을 기억해요.');
INSERT INTO sentence (content) VALUES ('현명한 금융 생활은 건강하고 행복한 삶을 위한 필수 요소예요.');
INSERT INTO sentence (content) VALUES ('금융 상식을 꾸준히 학습하여 경제적 자립을 이루는 멋진 사회초년생이 되세요!');